models/News.php
<?php

namespace app\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "tbl_news".
 *
 * @property integer $id
 * @property integer $id_category
 * @property integer $id_user
 * @property string $title
 * @property string $path
 * @property string $image
 * @property string $author_image
 * @property string $preview
 * @property string $text
 * @property string $tags
 * @property integer $position
 * @property integer $is_hot
 * @property integer $is_top
 * @property integer $is_visible
 * @property string $created
 * @property string $updated
 * @property string $meta_title
 * @property string $meta_description
 * @property string $meta_keywords
 *
 * @property TblNewsCategories $idCategory
 * @property TblUsers $idUser
 */
class News extends \yii\db\ActiveRecord
{

    public $searchontitle;
    public $updateDate;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tbl_news';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_category', 'id_user', 'title', 'preview', 'text'], 'required'],
            [['id_category', 'id_user', 'position', 'is_hot', 'is_top', 'is_visible', 'postponed'], 'integer'],
            [['preview', 'text'], 'string'],
            [['created', 'updated', 'postponed'], 'safe'],
            [['title', 'path', 'tags', 'meta_title', 'meta_description', 'meta_keywords'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_category' => 'Категория',
            'id_user' => 'Пользователь',
            'title' => 'Заголовок',
            'path' => 'Путь',
            'preview' => 'Аннотация',
            'text' => 'Текст',
            'tags' => 'Теги',
            'position' => 'Позиция',
            'is_hot' => 'Горячая новость',
            'is_top' => 'В топе',
            'is_visible' => 'Видимость',
            'created' => 'Добавлена',
            'updated' => 'Обновлена',
            'meta_title' => 'МЕТА: Заголовок',
            'meta_description' => 'МЕТА: Описание',
            'meta_keywords' => 'МЕТА: Ключевые слова',
            '_deleteimage' => 'Удалить изображение',
            'searchontitle' => 'Искать только в заголовках',
            'updateDate' => 'Изменить дату',
            'postponed' => 'Отложенная публикация',
        ];
    }

    public function getTopNews($place) 
    {
        $model = $this->find()->where('is_visible=1 AND is_top='.$place)->orderBy('created desc')->one();
        if($model)
            return $model;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(NewsCategories::className(), ['id' => 'id_category']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(Users::className(), ['id' => 'id_user']);
    }

    public function getImages()
    {
        return $this->hasMany(Images::className(), ['id_news' => 'id']);
    }

    public function getOneImage()
    {
        return $this->hasOne(Images::className(), ['id_news' => 'id']);
    }
}

models/SubscribeData.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "tbl_subscribe_data".
 *
 * @property integer $id
 * @property string $title
 * @property string $text
 */
class SubscribeData extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tbl_subscribe_data';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['count_news', 'count_sends'], 'integer'],
            [['title'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Название рассылки',
        ];
    }
}

controllers/SubscribeController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Subscribe;
use app\models\search\SubscribeSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SubscribeController implements the CRUD actions for Subscribe model.
 */
class SubscribeController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Subscribe models.
     * @return mixed
     */
    public function actionIndex()
    {
        $model = new Subscribe;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->render('create_subscribe', [
                'model' => $model,
                'message' => '<div id="modal-background" class="active"></div>
                <div id="modal-content" class="active">
                    <span id="modal-text">Вы успешно подписаны<br> на новостную рассылку</span>
                </div>',
            ]);
        } else {
            return $this->render('create_subscribe', [
                'model' => $model,
            ]);
        }
    }

    public function actionUnsubscribe() 
    {
        $model = new Subscribe;
        $message = '';
        if (Yii::$app->request->post()) {
            $find = $model->find()->where(['email' => Yii::$app->request->post()['Subscribe']['email']])->one();
            if($find) {
                $find->delete();
                
                $message = 'Вы успешно отписались от рассылки';
            }
        }

        return $this->render('unsubscribe', [
                'model' => $model,
                'message' => $message
            ]);
    }

    public function actionAdmin() 
    {
        $searchModel = new SubscribeSearch;
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());

        $this->layout = 'admin';
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * Displays a single Subscribe model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Subscribe model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Subscribe;
        $this->layout = 'admin';
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Subscribe model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $this->layout = 'admin';
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['admin']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Subscribe model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['admin']);
    }

    /**
     * Finds the Subscribe model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Subscribe the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Subscribe::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/SubscribeDataController.php
<?php

namespace app\controllers;

use Yii;
use app\models\SubscribeData;
use app\models\News;
use app\models\Subscribe;
use app\models\search\SubscribeDataSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\helpers\TextHelper;

/**
 * SubscribeDataController implements the CRUD actions for SubscribeData model.
 */
class SubscribeDataController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all SubscribeData models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SubscribeDataSearch;
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());
        $this->layout = 'admin';
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    public function actionSubscribers()
    {
        $model = new Subscribe;
        
        $this->layout = 'admin';
        return $this->render('subscribers', [
            'model' => $model->find()->all(),
            ]);
    }

    /**
     * Creates a new SubscribeData model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new SubscribeData;
        $news = new News;
        $subscribe = new Subscribe;
        $newsId = array();
        $current_date = date('d.m.Y', strtotime('now'));
        $yesterday_date = date('d.m.Y', strtotime('-1 day'));
        $getNews = $news->find()->where("FROM_UNIXTIME(created, '%d.%m.%Y') = '$current_date' OR FROM_UNIXTIME(created, '%d.%m.%Y') = '$yesterday_date' AND is_visible = '1'")->all();
        
        $sendEmail = $subscribe->find();
        if (Yii::$app->request->post()) {
            $model->load(Yii::$app->request->post());
            $sendNewsOne = false;

            if(isset($_POST['SubscribeData']['news'])) {
                foreach ($_POST['SubscribeData']['news'] as $key => $value) 
                    $newsId[] = $key;
            }

            //главная новость
            if(isset($_POST['SubscribeData']['news_index'])) {
                $sendNewsOne = $news->find()->where(['id' => $_POST['SubscribeData']['news_index']])->one();
            }

            $sendNews = $news->find()->where(['id' => array_unique($newsId)]);

            $mailInfo = array();
            $mailInfo['title'] = $_POST['SubscribeData']['title'];
            $mailInfo['day'] = TextHelper::getDay(time());
            $mailInfo['date'] = TextHelper::formatDate(time(), 'mt');
            $mailInfo['countNews'] = $sendNews->count();
            $message = $this->renderPartial('mail', [
                'sendNews' => $sendNews->all(),
                'sendNewsOne' => $sendNewsOne,
                'mailInfo' => $mailInfo,
            ]);

            $headers  = 'MIME-Version: 1.0' . "\r\n";
            $headers .= 'Content-type: text/html; charset=utf-8' . "\r\n";
            $headers .= 'From: АБН <noreply@abn.info>' . "\r\n";

            if(isset($_POST['SubscribeData']['emails'])) {
                $emails = $_POST['SubscribeData']['emails'];
                $count = 0;
                foreach ($emails as $email) {
                    $count++;
                    mail($email, $_POST['SubscribeData']['title'], $message, $headers);
                }
                $model->count_sends = $count;
            } else {
                $emails = $sendEmail->all();
                foreach ($emails as $email) {
                    mail($email->email, $_POST['SubscribeData']['title'], $message, $headers);
                }
                $model->count_sends = $sendEmail->count();
            }

            $model->count_news = $sendNews->count();
            
            if($model->save()){
                return $this->redirect(['index', 'id' => $model->id]);
            }
        } else {
            $this->layout = 'admin';
            return $this->render('create', [
                'model' => $model,
                'news' => $getNews,
                'emails' => $sendEmail->all()
            ]);
        }
    }

    /**
     * Deletes an existing SubscribeData model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the SubscribeData model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return SubscribeData the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = SubscribeData::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/subscribe-data/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\models\SubscribeData $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="subscribe-data-form">

    <?php $form = ActiveForm::begin(); ?>
	<ul class="nav nav-tabs" role="tablist">
      <li class="active"><a href="#home" role="tab" data-toggle="tab">Новости</a></li>
      <li><a href="#prop" role="tab" data-toggle="tab">Подписчики</a></li>
    </ul>
    <br>
    <div class="tab-content">
        <div class="tab-pane active" id="home">
            <?= $form->field($model, 'title')->textInput(['maxlength' => 255]) ?>
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>#</th>
                  <th>#</th>
                  <th>Изображение</th>
                  <th>Заголовок</th>
                  <th>Топ 1</th>
                  <th>Топ 2</th>
                  <th>Топ 3</th>
                  <th>Топ 4</th>
                  <th>Горячая новость</th>
                  <th>Добавлена</th>
                  <th>Обновлена</th>
                </tr>
              </thead>
              <tbody>
              	<?php foreach ($news as $row): ?>
        	        <tr>
        	          <th><input name="SubscribeData[news][<?=$row->id?>]" type="checkbox"></th>
        	          <th><input name="SubscribeData[news_index]" value="<?=$row->id?>" type="radio"></th>
                    <th>
                        <? $file = 'images/news/'.$row->id.'/thumb/'.md5($row->oneImage['image'].$row->id).'.png'; ?>
                        <? if($row->oneImage['image']): ?>
                            <img width="100" src="/<?=$file?>">
                        <? else: ?>
                            <center>-</center>
                        <? endif; ?>
                    </th>
        	          <th><?= $row->title; ?></th>
        	          <th><?= $row->is_top == 1 ? '<div style="background: #dff0d8; text-align: center">Да</div>' : '<center>Нет</center>'; ?></th>
        	          <th><?= $row->is_top == 2 ? '<div style="background: #dff0d8; text-align: center">Да</div>' : '<center>Нет</center>'; ?></th>
        	          <th><?= $row->is_top == 3 ? '<div style="background: #dff0d8; text-align: center">Да</div>' : '<center>Нет</center>'; ?></th>
        	          <th><?= $row->is_top == 4 ? '<div style="background: #dff0d8; text-align: center">Да</div>' : '<center>Нет</center>'; ?></th>
        	          <th><?= $row->is_hot ? '<div style="background: #fff9c2; text-align: center">Да</div>' : '<center>Нет</center>'; ?></th>
        	          <th><?= date('d.m.Y', $row->created); ?></th>
        	          <th><?= $row->updated ? date('d.m.Y', $row->updated) : '<center>-</center>'; ?></th>
        	        </tr>
                <?php endforeach; ?>
              </tbody>
            </table>

            <div class="form-group">
                <?= Html::submitButton($model->isNewRecord ? 'Добавить' : 'Сохранить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
        <div class="tab-pane" id="prop">
            <? foreach ($emails as $email): ?>
                <label><input name="SubscribeData[emails][]" type="checkbox" value="<?=$email->email?>" checked> <?=$email->email?></label><br>
            <? endforeach; ?>
        </div>

    </div>


</div>

views/subscribe-data/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\models\search\SubscribeDataSearch $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="subscribe-data-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'text') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/subscribe-data/create.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\SubscribeData $model
 */

$this->title = 'Создать';
$this->params['breadcrumbs'][] = ['label' => 'Рассылка', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="subscribe-data-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'news' => $news,
        'emails' => $emails,
    ]) ?>

</div>

views/subscribe-data/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\search\SubscribeDataSearch $searchModel
 */

$this->title = 'Рассылка';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="subscribe-data-index">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Создать', ['create'], ['class' => 'btn btn-success']) ?> <?= Html::a('Подписчики', ['subscribe/admin'], ['class' => 'btn btn-primary']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'attribute' => 'Заголовок',
                'format' => 'raw',
                'value' => function ($model) {                      
                        return $model->title;
                },
            ],
            [
                'attribute' => 'Новостей в рассылке',
                'format' => 'raw',
                'value' => function ($model) {                      
                        return $model->count_news;
                },
            ],
            [
                'attribute' => 'Кол-во адресатов',
                'format' => 'raw',
                'value' => function ($model) {                      
                        return $model->count_sends;
                },
            ],

            ['class' => 'yii\grid\ActionColumn',
                'template' => '{delete}',
            ],
        ],
    ]); ?>

</div>

views/subscribe-data/mail.php
<?
    use app\helpers\TextHelper;
    ?>
<meta charset="UTF-8"/>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tbody>
        <tr>
            <td bgcolor="#1e3f9a" align="center" style="width: 1316px; height: 500px; color: #FFFFFF">

                <table border="0" style="width: 700px; height: 200px;  color: #FFFFFF; background-image: url(http://abn.info/images/mail/top_bg.png); " >
                    <tr>
                        <td style="padding-left: 31px;  display: block; ">
                            <span style="background-color: red; font-family: PT Sans; font-weight: bold; padding: 0px 4px;text-transform: uppercase; font-size: 12px"><?= $mailInfo['day'] ?></span>
                              <span style="padding-right: 4px; font-family: PT Sans; font-size: 12px;"><?= $mailInfo['date'] ?></span>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding-left: 31px;  display: block; padding-right: 20px">
                            <img src="http://abn.info/images/mail/logo_abn.png">
                            <hr style="color: #4b61a0;  background-color:#4b61a0; border:0px none; height:1px; clear:both; display: block;margin-top: 15px;margin-bottom: 0px;">
                        </td>
                    </tr>
            <!--         <tr>
                        <td></td>
                    </tr> -->
                    <tr valign="top">
                        <td style="font-size: 24px; font-family: PT Sans; font-weight: bold;  text-transform: uppercase; padding-left: 28px; "><?= $mailInfo['title'] ?></td>
                    </tr>
                    <tr>
                        <td></td>
                    </tr>
                </table>
                      
                <!-- Блок для главной новости -->
                <table style="width: 700px; height: 220px; background: #2c2c2c;">
                    <tr>
                    	<? if($sendNewsOne->oneImage): ?>
	                        <td style="padding-left: 28px; width: 200px">
		                            <?php 
		                                $file = "http://abn.info/images/news/".$sendNewsOne->id."/thumb/".md5($sendNewsOne->oneImage->image.$sendNewsOne->id).'-306x180.png';
		                                ?>
		                            <img src="<?= $file ?>" width="263" height="152">
	                        </td>
                        <? endif; ?>
                        <td style="width: 370px; <?=!$sendNewsOne->oneImage ? 'padding-left: 28px;' : '' ?>">
                            <span style="color: #ffffff; font-size: 22px; font-weight: bold; width: 360px; display: block; padding-bottom: 5px;">
                                <a target="_blank" style="color: #ffffff; font-family: PT Sans; line-height: 25px;  text-decoration: none;" href="http://abn.info/news/<?=$sendNewsOne->category->path?>/<?=$sendNewsOne->path?>"><?=$sendNewsOne->title?></a>
                            </span>

                            <span style="color: #aeaeae; font-family: arial; font-size: 12px; width: 360px; display: block; padding-bottom: 5px;"><?=$sendNewsOne->preview?></span>
                            <span style="font-size: 10px; font-family: PT Sans; color: #8f8f8f; padding-top: 2px; background-image: url('http://abn.info/images/mail/clock_white.png');background-position: left center;background-repeat: no-repeat;padding-left: 19px;"><?=TextHelper::formatDate($sendNewsOne->created, 'mt')?></span> 
                            <a target="_blank" href="http://abn.info/news/category/<?=$sendNewsOne->category->path?>" style="border-radius: 2px;font-family: 'Arial';letter-spacing: 1px;font-size: 7px;color: white;font-weight: bold;padding: 3px 5px;text-decoration: none;text-transform: uppercase;line-height: 20px; background-color: #306cc7"><?=$sendNewsOne->category->title?></a>
                        </td>
                    </tr>
                </table>
                
                <!-- Остальные новости -->
                <table style="width: 700px; background: #ffffff; padding-top: 10px;">
                    <tr>
                        <td colspan="2"></td>
                    </tr>
                    <tr>
                        <td colspan="2"></td>
                    </tr>
                    <? $i = 0; foreach ($sendNews as $news): $i++; ?>  

                    <tr >
                    	<? if($news->oneImage): ?>
                        <td style="padding-left: 28px; width: 140px; vertical-align: top;">
	                            <?php 
	                                $file = "http://abn.info/images/news/".$news->id."/thumb/".md5($news->oneImage->image.$news->id).'-306x180.png';
	                                ?>
	                            <img src="<?= $file ?>" width="117" height="77">
                        </td>
                        <? endif; ?>
                        <td style="width: 540px; <?=!$news->oneImage ? 'padding-left: 28px; ' : '' ?> padding-right: 28px; vertical-align: top;" colspan="2">
                            <span style="font-size: 10px; display: block; padding-bottom: 2px; font-family: PT Sans; color: #948c8c; background-image: url('http://abn.info/images/mail/clock.png');background-position: left center;background-repeat: no-repeat;padding-left: 19px;">
                                <?=TextHelper::formatDate($news->created, 'mt')?> / 
                            <span style="text-transform: uppercase;">
                                <a target="_blank" display: block; padding-bottom: 5px; style="color: #948c8c; text-decoration: none; font-family: PT Sans; line-height: 16px;" href="http://abn.info/news/category/<?=$news->category->path?>"><?=$news->category->title?></a>
                            </span>
                            </span> 
                            <span style="color: #000000; font-size: 16px; font-weight: bold; font-family: PT Sans; display: block; padding-bottom: 5px;">
                                <a target="_blank" style="color: #000000; text-decoration: none; font-family: PT Sans;  display: block; line-height: 18px;" href="http://abn.info/news/<?=$news->category->path?>/<?=$news->path?>"><?=$news->title?></a>
                            </span>
                            <span style="color: #000000; font-family: arial; font-size: 12px; "><?=$news->preview?></span>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding-left: 28px; padding-bottom: 20px; padding-right: 28px;" colspan="2">
                            <?= $mailInfo['countNews'] == $i ? '' : '<hr style="color: #dedede;  background-color:#dedede; border:0px none; height:1px; clear:both; display: block;margin-top: 15px;margin-bottom: 0px;">' ?>
                        </td>
                    </tr>
                    <? endforeach; ?>
                    <tr>
                        <td style="padding-left: 28px; " colspan="2">
                            <a target="_blank" href="http://abn.info/"><img src="http://abn.info/images/mail/more-news.png"></a>
                            <br>
                            <br>
                        </td>
                    </tr>
                </table>
               
                
                <!-- Подвал -->
                <table style="width: 700px; height: 138px; background: #2c2c2c;">
                    <tr>
                        <td style="padding-left: 28px; ">
                            <span style="font-family: PT Sans; font-weight: bold; font-size: 12px; color: #ffffff">
                            Расслыка ЗАО «Агентство бизнес-новостей». <a style="color: #ffffff; " target="_blank" href="http://abn.info/unsubscribe">Отписаться от этой рассылки</a>
                            </span>
                            <br><br>
                            <span style="font-family: arial; font-size: 9px; color: #818181; padding-top: 10px">
                            Все права на материалы и новости, опубликованные на сайте, охраняются в соответствии с законодательством РФ. Допускается цитирование
                            без согласования с редакцией не более 50% от объема оригинального материала, с обязательной прямой гиперссылкой на страницу, с которой материал заимствован. Гиперссылка должна размещаться непосредственно в тексте, воспроизводящем оригинальный материал, до или после цитируемого блока.
                            </span>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>

views/subscribe-data/subscribers.php
<?
use yii\helpers\Html;
$this->title = 'Подписчики';
$this->params['breadcrumbs'][] = ['label' => 'Рассылка', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="subscribe-data-index">
    <h1><?= Html::encode($this->title) ?></h1>
	<table class="table table-striped table-bordered">
	    <thead>
	        <tr>
	            <th>#</th>
	            <th>Электронная почта</th>
	        </tr>
	    </thead>
	    <tbody>
	        
        	<? $i = 0; foreach ($model as $row): $i++;?>
	        	<tr data-key="1">
	        		<td><?= $i ?></td>  
	            	<td><?= $row->email ?></td>
	            </tr>  
        	<? endforeach; ?>
	            
	        
	    </tbody>
	</table>
</div>