controllers/NewsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\News;
use app\models\NewsCategories;
use app\models\Images;
use app\models\search\NewsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\helpers\TextHelper;
use app\helpers\YiiHelper;
use yii\web\UploadedFile;
use yii\web\Request;
use yii\imagine\Image;
use yii\data\Pagination;
/**
 * NewsController implements the CRUD actions for News model.
 */
class NewsController extends Controller
{
    public $enableCsrfValidation = false; //Отключаем csfr валидацию, иначе не будет работать загрузка изображений и файлов
    public $pageSize = 10;

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all News models.
     * @return mixed
     */
    public function actionIndex()
    {
        if(!YiiHelper::is_auth())
            $this->redirect('/users/login');

        $searchModel = new NewsSearch;

        if(isset($_GET['id'])) {
            $categoryInfo = NewsCategories::findOne($_GET['id']);
            $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());
             $categories = NewsCategories::find()->where(['is_visible' => 1])->all();
            $this->layout = 'admin';
            return $this->render('index', [
                'dataProvider' => $dataProvider,
                'searchModel' => $searchModel,
                'categoryInfo' => $categoryInfo,
                'categories' => $categories,
            ]);
        } else {
            $categories = NewsCategories::find()->where(['is_visible' => 1])->all();
            $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());
            $this->layout = 'admin';
            return $this->render('index', [
                'dataProvider' => $dataProvider,
                'searchModel' => $searchModel,
                'categories' => $categories,
            ]);
        }
        
    }

    public function actionAll()
    {
        $query = News::find()->where(['is_visible' => 1])->orderBy("created desc");
        $this->layout = 'twocolumn';
        return $this->render('all', [
                'model' => $query->limit($this->pageSize)->all(),
                'count' => $query->count(),
                'pageSize' => $this->pageSize,
            ]);
    }

    public function actionPage()
    {
        if(Yii::$app->getRequest()->getIsAjax()):
            $query = News::find()->where(['is_visible' => 1])->orderBy("created desc");
            $countQuery = clone $query;
            $pages = new Pagination(['totalCount' => $countQuery->count()]);
            $pages->setPageSize($this->pageSize);
            $models = $query->offset($pages->offset)->limit($pages->limit)->all();
            $max_pages = $countQuery->count() / $this->pageSize;
            if($_POST['current_page'] > $max_pages) {
                return false;
            } else {
                $this->layout = 'no-layout';
                return $this->renderPartial('_page', [
                    'model' => $models,
                    'pages' => $pages,
                ]);
            }
        endif;
    }

    public function actionArchive($date)
    {
        $model = NewsCategories::find()->where(['is_visible' => 1])->all();

        return $this->render('archive', [
                'model' => $model,
                'date' => $date
            ]);
    }

    /**
     * Displays a single News model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id=null, $path=null)
    {   
        $model = $this->findModel($id, $path);
        
        if(!empty($model->postponed) || $model->is_visible != 1) 
            throw new NotFoundHttpException();

        $otherNews = News::find()->where(['is_visible' => 1, 'id_category' => $model->category->id])->andWhere(['not like', 'id', $model->id])->limit(4)->orderBy("created desc")->all();
        $linkNews = News::find()->where(['is_visible' => 1])->andWhere(['not like', 'id', $model->id])->andWhere(['like', 'tags', $model->tags])->limit(3)->orderBy("created desc")->all();
        
        $this->layout = 'news';

        return $this->render('view', [
            'model' => $model,
            'otherNews' => $otherNews,
            'linkNews' => $linkNews,
        ]);
    }

    /**
     * Creates a new News model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if(!YiiHelper::is_auth())
            $this->redirect('/users/login');

        $id = $_GET['id'];
        $model = new News;
        if(isset($id))
            $model->id_category = $id;
        $categoryInfo = NewsCategories::findOne($id);

        if (Yii::$app->request->post()) {

            $model->load(Yii::$app->request->post());
            $model->id_user = YiiHelper::getAuthId();

            if(!empty(Yii::$app->request->post()['News']['created']))
                $model->created = strtotime(Yii::$app->request->post()['News']['created']." ".date("h:i:s"));
            else
                $model->created = time();

            if(!empty(Yii::$app->request->post()['News']['postponed'])) {
                $model->postponed = strtotime(Yii::$app->request->post()['News']['postponed']);
                $model->is_visible = 0;
            }

            $model->path = $id . date('ds', time()) .'-'. TextHelper::translite(Yii::$app->request->post()['News']['title']);

            if($model->save()) {
                $this->uploadImage($model->id);
                Yii::$app->getCache()->set('updateNews', true);
                Yii::$app->session->setFlash('flashMessage', array('success', 'Новая новость добавлена.'));
                return $this->redirect(['update', 'id' => $model->id]);
            }
        } else {
            $this->layout = 'admin';
            return $this->render('create', [
                'model' => $model,
                'categoryInfo' => $categoryInfo,
            ]);
        }
    }

    /**
     * Updates an existing News model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        if(!YiiHelper::is_auth())
            $this->redirect('/users/login');

        $model = $this->findModel($id);
        $currentDate = $model->created;
        $model->created = date('d.m.Y', $model->created);
        if(!empty($model->postponed))
            $model->postponed = date('d.m.Y H:i', $model->postponed);

        if (Yii::$app->request->post()) {
            $model->load(Yii::$app->request->post());

            $model->created = $currentDate;

            if(Yii::$app->request->post()['News']['updateDate'] == 1) {
                if(!empty(Yii::$app->request->post()['News']['created']))
                    $model->created = strtotime(Yii::$app->request->post()['News']['created']." ".date("H:i"));
                else
                    $model->created = time();
            }

            if(!empty(Yii::$app->request->post()['News']['postponed'])) {
                $model->postponed = strtotime(Yii::$app->request->post()['News']['postponed']);
                $model->is_visible = 0;
            }
            
            $model->updated = time();

            if($model->save()) {
                $this->uploadImage($id);
                Yii::$app->getCache()->set('updateNews', true);
                Yii::$app->session->setFlash('flashMessage', array('success', 'Новость "'.$model->title.'" успешно изменена.'));
                return $this->redirect(['index']);
            }
        } else {
            $this->layout = 'admin';
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function uploadImage($id)
    {
        if(isset($_FILES['News'])) {
            $dirUpload = 'images/news/';
            if(!file_exists($dirUpload.$id)) {
                mkdir($dirUpload.$id);
                mkdir($dirUpload.$id.'/thumb');
            }
            $i = -1;
            foreach ($_FILES['News']['name']['image'] as $image) {
                $i++;
                $tmpName = $_FILES['News']['tmp_name']['image'][$i];
                $ext = pathinfo($image, PATHINFO_EXTENSION);
                $imageName = md5(date($image.date('dmYhis'))).'.'.$ext;
                if(move_uploaded_file($tmpName, $dirUpload.$id.'/'.$imageName)) {
                    $model = new Images;
                    $model->id_news = $id;
                    $model->image = $imageName;
                    $model->author = Yii::$app->request->post()['News']['image_authorc'][$i];
                    $model->text = Yii::$app->request->post()['News']['image_previewc'][$i];
                    $model->save();

                    //preview
                    $file = 'images/news/'.$id.'/thumb/'.md5($imageName.$id);
                    Image::thumbnail('images/news/'.$id.'/'.$imageName, 200, 200)->save($file.'.png', ['quality' => 1]); 
                    Image::thumbnail('images/news/'.$id.'/'.$imageName, 115, 76)->save($file.'-115x76.png', ['quality' => 1]); 
                    Image::thumbnail('images/news/'.$id.'/'.$imageName, 306, 180)->save($file.'-306x180.png', ['quality' => 1]); 
                    Image::thumbnail('images/news/'.$id.'/'.$imageName, 467, 257)->save($file.'-467x257.png', ['quality' => 1]); 
                }
            }
        }

        if(Yii::$app->request->post()['News']['image_new'] !== 1 && isset(Yii::$app->request->post()['News']['image_author'])) {
            $model = new Images;

controllers/PagesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Pages;
use app\models\search\PagesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\helpers\TextHelper;
use app\helpers\YiiHelper;

/**
 * PagesController implements the CRUD actions for Pages model.
 */
class PagesController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Pages models.
     * @return mixed
     */
    public function actionIndex()
    {
        if(!YiiHelper::is_auth())
            $this->redirect('/users/login');

        $searchModel = new PagesSearch;
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());
        $this->layout = 'admin';
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * Displays a single Pages model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id=null, $path=null)
    {
        return $this->render('view', [
            'model' => $this->findModel($id, $path),
        ]);
    }

    /**
     * Creates a new Pages model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if(!YiiHelper::is_auth())
            $this->redirect('/users/login');

        $model = new Pages;

        if (Yii::$app->request->post()) {
            $model->load(Yii::$app->request->post());
            $model->path = TextHelper::translite(Yii::$app->request->post()['Pages']['title']);
            if($model->save()) {
                Yii::$app->session->setFlash('flashMessage', array('success', 'Новая текстовая страница добавлена.'));
                return $this->redirect(['update', 'id' => $model->id]);
            }
        } else {
            $this->layout = 'admin';
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Pages model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        if(!YiiHelper::is_auth())
            $this->redirect('/users/login');

        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('flashMessage', array('success', 'Текстовая страница "'.$model->title.'" успешно изменена.'));
            return $this->redirect(['index', 'id' => $model->id]);
        } else {
            $this->layout = 'admin';
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Pages model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if(!YiiHelper::is_auth())
            $this->redirect('/users/login');

        $model = $this->findModel($id);
        Yii::$app->session->setFlash('flashMessage', array('success', 'Текстовая страница "'.$model->title.'" удалена.'));
        $model->delete();
        return $this->redirect(['index']);
    }

    /**
     * Finds the Pages model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Pages the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id=null, $path=null)
    {
        if ($id) {
            $model = Pages::find()->where(['id'=>$id])->one();
        } elseif ($path) {
            $model = Pages::find()->where(['path'=>$path])->one();
        }
        if ($model !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/TextblocksController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Textblocks;
use app\models\search\TextblocksSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TextblocksController implements the CRUD actions for Textblocks model.
 */
class TextblocksController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Textblocks models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TextblocksSearch;
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());
        $this->layout = 'admin';
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * Updates an existing Textblocks model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index', 'id' => $model->id]);
        } else {
            $this->layout = 'admin';
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Textblocks model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Textblocks model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Textblocks the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Textblocks::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/layouts/admin.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use app\models\NewsCategories;
use app\helpers\YiiHelper;

/**
 * @var \yii\web\View $this
 * @var string $content
 */
AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    
    <link href="/css/admin.css" rel="stylesheet">

    <link href="/images/fav.png" rel="shortcut icon" />
</head>
<body>
<?php $this->beginBody() ?>
    <div class="wrap">
        <?php
            NavBar::begin([
                'brandLabel' => 'На сайт',
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => [
                    !YiiHelper::is_auth() ?
                        ['label' => 'Авторизация', 'url' => ['/users/login']] :
                        ['label' => 'Выход (' . YiiHelper::getAuthName() . ')',
                            'url' => ['/users/logout'],
                            'linkOptions' => ['data-method' => 'post']],
                ],
            ]);
            NavBar::end();
        ?>
      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
            <?php
                $news_categories = array();
                $news_categories[] = "<li class='dropdown-header'>Управление новостями</li>";
                $news_categories[] = array('label'=>'Управление категориями', 'url' => '/news-categories/index');
                $news_categories[] = array('label'=>'Все новости', 'url' => '/news/index');
                $news_categories[] = "<br><li class='dropdown-header'>Категории</li>";
                foreach (NewsCategories::find()->where('is_visible=1')->all() as $category):
                    $news_categories[] = array('label'=>$category->title, 'url' => '/news/index/'.$category->id);
                endforeach;
             ?>
            <?php echo Nav::widget([
                'options' => ['class'=>'nav nav-sidebar'],
                'items' => [
                    ['label' => 'Панель новостей', 'url' => ['/news/index']],
                    ['label' => 'Текстовые страницы', 'url' => ['/pages/index']],
                    ['label' => 'Текстовые блоки', 'url' => ['/textblocks/index']],
                    ['label' => 'Баннеры', 'url' => ['/banners/index']],
                    ['label' => 'Новости',
                        'items' => $news_categories,
                    ],
                    ['label' => 'Рассылка', 'url' => ['/subscribe-data/index']],
                    ['label' => 'Редакция', 'url' => ['/users/index']],
                ],
            ]);
            ?>
          </div>
          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header">Панель администратора</h1>
              <?= Breadcrumbs::widget([
                  'homeLink' => false,
                  // 'homeLink' => ['label' => 'Панель новостей', 'url' => '/news/index'],
                  'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
              ]) ?>
              <?= $content ?>
          </div>
        </div>
      </div>
 
    </div>

   
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/twocolumn.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use app\widgets\HomeWidget;
use app\widgets\NewsScrollBlockWidget;
use app\widgets\MiniMenuWidget;
use app\helpers\YiiHelper; 
use app\helpers\TextHelper; 
use yii\caching\Cache;

/**
 * @var \yii\web\View $this
 * @var string $content
 */
// AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= Html::encode($this->title) ?></title>
    <meta content="width=device-width, initial-scale=0.3,maximum-scale=3,user-scalable=1" name="viewport">
    <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
    <title>Главная | АБН</title>
    <meta name="description" content=" " />
    <meta name="keywords" content=" " />
    <!-- <base href="http://www.abn.info/"></base> -->
    
    <link href='http://fonts.googleapis.com/css?family=PT+Sans+Caption:700|PT+Sans:400,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/styles/style.css" type="text/css" media="screen, projection" />
    <link rel="stylesheet" href="/styles/jquery.jscrollpane.css"/>
    <!--[if IE]><link rel="stylesheet" href="/styles/style_ie.css" type="text/css" media="screen, projection" /><![endif]--> 
    
    <script src="/js/jquery-1.10.2.min.js"></script> 
    <script src="/js/jquery.jscrollpane.min.js"></script>
    <script src="/js/jquery.mousewheel.js"></script> 
    <script src="/js/modernizr-2.5.3.min.js"></script>
    <script src="/js/jquery.hc-sticky.js"></script>
    <script src="/js/script.js"></script>
    <link href="/images/fav.png" rel="shortcut icon" />
     
        
</head>

<body>
<?php $this->beginBody() ?>
    <section id="miniheader">
       <div class="miniheaderwrap">
         <table cellpadding="0" cellspacing="0" border="0" width="100%">
         <tr>
         <td align="left" valign="top">
            <div class="minilogo"><a href="/"><img src="/images/minilogo.png" title="АБН" border=0 ></a></div>
         </td>   
         <td align="left" valign="top">
            <nav>
                 <ul class="minimainmenu">
                    <?= MiniMenuWidget::widget(); ?>
                </ul>
            </nav>      
         </td>   
         <td align="left" valign="top"><a href="#" class="datepicker_link_mini"><span></span></a></td>   
         <td align="left" valign="top"><a href="#" class="searchform_link_mini"><span></span></a></td>
         </tr>
         </table>
         <div class="search_form_mini">
                        <form id="search_mini" action="/search" method="get" class="search">
                        <input type="text" name="search" value="" placeholder="Что ищем?">
                        <input type="submit" value="">
                        <a href="#" class="close_mini_search"></a>
                        </form>         
         </div>      
       </div>   
    </section>  

    
<div id="wrapper">
<div id="wrapperpage">

    <header id="header">
        
        <section class="today_area">
        <div class="today_block">
          <span class="day_name"><?= TextHelper::getDay(time()) ?></span> <span><?= TextHelper::formatDate(time(), 'm') ?></span>
          <span class="last_post_date">актуализация - <?= Yii::$app->getCache()->get('lastUpdate') ?> мск</span>
        </div>
        <div class="rss">
          <span class="rss"><a target="_blank" href="/rss"><span class="icon">RSS</span></a></span>
        </div>
        </section>
        
        <section class="cls">
           <div class="logo"><a href="/"><img src="/images/logo.png" title="АБН" border=0 ></a></div>
           <div class="submenu">
              <div class="cls">


                 <div class="area_search">
                        <form id="search" action="/search" method="get" class="search">
                        <input type="text" id='msearch' name="search" value="<?= isset($_GET['search']) ? $_GET['search'] : '' ?>" placeholder="Поиск по сайту">
                        <input type="submit" value="">
                        </form>
                 </div>           
                 
                 <div class="area_celendar">
                  <a href="#" class="datepicker_link">Архив</a>
                 </div>
                 
                 <div class="area_curs">
                   <div class="area_curs_title">Официальные курсы:</div>
                   <div class="area_curs_block"><div style="clear: both"><?= Yii::$app->getCache()->get('lastCurrency') ?> </div></div>
                 </div>

                 
              </div>                
           </div>
        </section>

        <?= HomeWidget::widget(); ?>
        
        <section <?= (Yii::$app->request->getUrl() !== '/') ? 'id="content" class="content_index_topblock1"' : 'id="index_main_content_block"' ?>>
           <table cellpadding="0" cellspacing="0" border="0">
            <tr>
            <td align="left" valign="top">
                <?=$content?>
            </td>   
            <td align="left" valign="top">
               <section class="partner_block <?= (Yii::$app->request->getUrl() !== '/') ? 'partner_block_nomargin' : '' ?>">
                    <? if(Yii::$app->request->getUrl() !== '/'): ?>
                        <a href="#"><img src="/images/240.jpg" border="0" width="240" height="400"></a>
                    <? endif; ?>
<!--                    <div class="part_block_title">Партнеры агентства</div>-->
<!--                    <div class="part_block_content">-->
<!--                            <div id="smi2adblock_79241"><a href="http://net.finam.ru/">Новости net.finam.ru</a></div>-->
<!--                                <script type="text/javascript" charset="utf-8">-->
<!--                                  (function() {-->
<!--                                    var sc = document.createElement('script'); sc.type = 'text/javascript'; sc.async = true;-->
<!--                                    sc.src = 'http://news.net.finam.ru/data/js/79241.js'; sc.charset = 'utf-8';-->
<!--                                    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(sc, s);-->
<!--                                  }());-->
<!--                                </script>-->
<!--                            </div>-->
<!--                        </div>-->
                    
                    
               </section>
            </td>    
            </tr>
           </table>
        </section>
        
        

    </section><!-- #content-->
</div><!-- #wrapperpage -->
</div><!-- #wrapper -->

<footer id="footer">
    <nav>
        <ul class="footmenu">
            <li><a href="/pages/ob-agentstve" >Об агентстве</a></li>
            <li><a href="/forum">Форум</a></li> 
            <li><a href="/contacts" >Контакты</a></li>
            <li><a target="_blank" href="/rss" ><span class="icon">RSS-подписка</span></a></li> 
        </ul>
    </nav>
    <section class="footcontent">
    <table cellpadding="0" cellspacing="0" border="0" width="100%">
    <tr>
    <td align="left" valign="top"><div class="footlogo"><a href="/"><img src="/images/footlogo.png" title="АБН" border=0 ></a></div>
      <div class="cross-link">
        </div>
    </td>     
    <td align="left" valign="top">
    <div class="footcopy"><p><?=YiiHelper::getTextblock("Подвал: копирайт")?></p></div>
     <div class="foottext"><?=YiiHelper::getTextblock("Подвал: инфа")?></div>
      <div class="footbanners">
      <?=YiiHelper::getTextblock("Подвал: счетчики")?>
      </div>
    </td>
    </tr>
    </table>
    </section>
</footer><!-- #footer -->
<a class="scrollup" href="#"></a>
<div id="fade"></div>

    <script src="/js/picker.js"></script>
    <script src="/js/picker.date.js"></script>
    
    <link rel="stylesheet" href="/js/themes/classic.css" >
<link rel="stylesheet" href="/js/themes/classic.date.css" >
    
<script type="text/javascript">
$(document).ready(function(){
            
    $(window).scroll(function(){
        if ($(this).scrollTop() > 100) {
            $('.scrollup').fadeIn();
        } else {
            $('.scrollup').fadeOut();
        }
    });

    $('.scrollup').click(function(){
    $("html, body").animate({ scrollTop: 0 }, 600);
        return false;
    });
    
    
 var shrinkHeader = 300;
  $(window).scroll(function() {
    var scroll = getCurrentScroll();
      if ( scroll >= shrinkHeader ) {
           $('#miniheader').show();
        }
        else {
           $('#miniheader').hide();
        }
  });
function getCurrentScroll() {
    return window.pageYOffset;
    }   
    
    
    var rscroll = getCurrentScroll();
      if ( rscroll >= shrinkHeader ) {
           $('#miniheader').show();
        }
        else {
           $('#miniheader').hide();
        }   
    
    $('.datepicker_link, .datepicker_link_mini').pickadate({
        onSet: function() {
          var zref = this.get();
            if (zref=='') return false;
            //alert(zref);
          window.location = '/news/archive/'+zref;
        },
        onClose: function() { $('#fade').fadeOut(); } ,
        monthsFull: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
        weekdaysShort: ['ВС', 'ПН', 'ВТ', 'СР', 'ЧТ', 'ПТ', 'СБ'],
        firstDay: 1,
        clear: '',
        today: '',
        //highlight: '2014-05-05',
        //picker.set('highlight', [2014,5,20]),
        format: 'dd-mm-yyyy',
        max: true     
    });
    
    $('.datepicker_link_mini, .datepicker_link').click(function(){ $('#fade').css({'filter' : 'alpha(opacity=80)'}).fadeIn(); return false });
    
        
    
     var picker = $('.datepicker_link, .datepicker_link_mini').pickadate('picker');
    //picker.set('select', [2013,3,20], { muted: true });
    
    $('.searchform_link_mini').click(function(){ 
      $('.search_form_mini').show();
      return false 
    }); 
    $('.close_mini_search').click(function(){ 
      $('.search_form_mini').hide();
      return false 
    });
    
    
    
    $('.lenta_block_scroll').css("height", (($(window).height())-160)  + "px"); 
    $(window).resize(function() {
        $('.lenta_block_scroll').css("height", (($(window).height())-160)  + "px"); 
    });
    
    $('.lenta_block_scroll').jScrollPane();
    $('.lenta_block').hcSticky({top: 40});
});
</script>

<!-- <?php $this->endBody() ?> -->
</body>
</html>
<?php $this->endPage() ?>